var articlesKids =
 [
    { "id": "art1K", "img": "images/f11.png.jpg", "imgS1": "images/f12.jpg", "imgS2": "images/f13.jpg", "imgS3": "images/f14.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 40, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art2K", "img": "images/f21.jpg", "imgS1": "images/f22.jpg", "imgS2": "images/f23.jpg", "imgS3": "images/f24.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 5, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art3K", "img": "images/f31.jpg", "imgS1": "images/f31.jpg", "imgS2": "images/f33.jpg", "imgS3": "images/f34.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 30, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art4K", "img": "images/f41.jpg", "imgS1": "images/f42.jpg", "imgS2": "images/f43.jpg", "imgS3": "images/f41.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 35, "desc": "hey hey " },
    { "id": "art5K", "img": "images/f51.jpg", "imgS1": "images/f52.jpg", "imgS2": "images/f53.jpg", "imgS3": "images/f51.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 25, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art6K", "img": "images/f61.jpg", "imgS1": "images/f62.jpg", "imgS2": "images/f63.jpg", "imgS3": "images/f64.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 70, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art7K", "img": "images/f71.jpg", "imgS1": "images/f71.jpg", "imgS2": "images/f72.jpg", "imgS3": "images/f73.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 50, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art8K", "img": "images/f81.jpg", "imgS1": "images/f81.jpg", "imgS2": "images/f83.jpg", "imgS3": "images/f82.jpg", "marque": "jessamine", "name": "Bodysuit", "price": 60, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art9K", "img": "images/f91.jpg", "imgS1": "images/f91.jpg", "imgS2": "images/f92.jpg", "imgS3": "images/f93.jpg", "marque": "jessamine", "name": "sneakers", "price": 49, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art10K", "img": "images/101.jpg", "imgS1": "images/102.jpg", "imgS2": "images/103.jpg", "imgS3": "images/101.jpg", "marque": "jessamine", "name": "sneakers", "price": 39, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art11K", "img": "images/111.jpg", "imgS1": "images/113.jpg", "imgS2": "images/112.jpg", "imgS3": "images/111.jpg", "marque": "jessamine", "name": "sockes", "price": 19, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
    { "id": "art12K", "img": "images/121.jpg", "imgS1": "images/123.jpg", "imgS2": "images/122.jpg", "imgS3": "", "marque": "jessamine", "name": "hat", "price": 50, "desc": "made from high-quality, soft cotton that feels amazing against your skin  fabric is breathable and durable, so you can wear it for years to come .Our product are also ethically made, which means that you can feel good about your purchase knowing that it was made with care for both the environment and the people involved in the manufacturing process." },
];
